apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: astarion
  name: jwt
spec:
  selector:
    matchLabels:
      app: jwt
  template:
    metadata:
      labels:
        app: jwt
    spec:
      containers:
        - name: jwt
          image: 982402893832.dkr.ecr.ap-northeast-2.amazonaws.com/astarion-jwt:0.1
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "8082"
          envFrom:
          - secretRef:
              name: astarion-jwt-secret
      imagePullSecrets:
        - name: aws-ecr-secret
